### ISSUE TITLE
Question #13

### ISSUE THREAD

**Issue by jm2292236** [learn-co-curriculum/phase-2-quiz-state-and-events#2]
It says "select all that apply" but is using radio buttons instead of check boxes.

**Comment by jm2292236** [comment]
Hello, Liz.  This is the link: https://my.learn.co/courses/381/quizzes/2248?module_item_id=41959

________________________________

**Comment by lizbur10** [comment]
Thanks for bringing this to our attention! The question has now been updated. 💙
